parser: babel-eslint

extends:
  - airbnb
  - plugin:flowtype/recommended

plugins:
  - flowtype

parserOptions:
  ecmaVersion: 8
  sourceType: script
  ecmaFeatures:
    experimentalObjectRestSpread: true

rules:

  semi:
    - error
    - never

  object-curly-newline:
    - error
    - consistent: true

  jsx-quotes:
    - error
    - prefer-single

  import/prefer-default-export: off

  jsx-a11y/alt-text: off

  react/jsx-filename-extension:
    - error
    - extensions:
      - .js

  flowtype/boolean-style:
    - error
    - bool

  flowtype/delimiter-dangle:
    - error
    - always-multiline

  flowtype/generic-spacing:
    - error
    - never

  flowtype/semi:
    - error
    - never

  flowtype/type-id-match:
    - error
    - ^[A-Z][a-z0-9]*
